# Do the npm install in the full image
FROM mhart/alpine-node AS builder
WORKDIR /app
COPY package.json .
RUN npm config set strict-ssl false
RUN npm install
RUN npm build
COPY . .

# And then copy over node_modules, etc from that stage to the smaller base image
FROM mhart/alpine-node:base
WORKDIR /app
COPY --from=builder /app .
EXPOSE 8080
CMD ["node_modules/.bin/next", "start"]